Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -59,12 +59,13 @@ jobs:
       - name: Build Docker Image
         run: |
           docker build -t $IMAGE_NAME:$TAG .
+          docker images
 
-      - name: Run Docker Container
-        run: |
-          docker run -d -p 8080:8080 --name $CONTAINER_NAME $IMAGE_NAME:$TAG
-          sleep 10  # give it time to boot
-          curl --fail http://localhost:8080 || echo "App is not responding"
+      # - name: Run Docker Container
+      #   run: |
+      #     docker run -d -p 8080:8080 --name $CONTAINER_NAME $IMAGE_NAME:$TAG
+      #     sleep 10  # give it time to boot
+      #     curl --fail http://localhost:8080 || echo "App is not responding"
 
       # - name: Stop and Remove Docker Container
       #   if: always()
